name: Release on tag

on:
  push:
    branch: master

jobs:
  build-and-release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git make inkscape x11-apps

    - name: Build dist-folders
      run: make build

    - name: Generate tar-files
      run: make dist/material_*cursors

    - name: Upload tar files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: material-cursors
        path: material_*cursors*.tar.gz
