name: Release on tag

on:
  push:
    branches: "master"

jobs:
  build-and-release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git make inkscape x11-apps
    - name: Build dist-folders
      run: make build

    - name: Generate tar-files
      run: make dist/material_*cursors

    # Шаг 6: Хранение артефактов сборки
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: material_*cursors*.tar.gz
